### ISSUE TITLE
Updating code to match with latest version of FontAwesome

### ISSUE THREAD

**Issue by armudgal** [hummingbird-dev/hummingbird-treeview#11]
FontAwesome changed their syntax from using `fa` to two different types of icon, solid:`fas` and regular:`far` and this should be changed in the code as well.

Ref: https://fontawesome.com/how-to-use/on-the-web/setup/upgrading-from-version-4

Code change:
https://github.com/hummingbird-dev/hummingbird-treeview/blob/4245bcf75b4dbf5e6f5d58db8960f9591a576de4/hummingbird-treeview.js#L104
https://github.com/hummingbird-dev/hummingbird-treeview/blob/4245bcf75b4dbf5e6f5d58db8960f9591a576de4/hummingbird-treeview.js#L616-L620

Removing `fa` and mentioning in the docs to use the icon class with either `fas` or `far` should do the job.
Thank you

**Comment by hummingbird-dev** [comment]
Well, I don't want to force to move from version 4 to version 5 at the moment. Maybe I can include that in a dynamic way to either use version 4 or version 5. By default it would expect v4 and with an option, which the user can set, it would be possible to use v5. Would that be a way to go?

**Comment by armudgal** [comment]
I think that would work brilliantly.

**Comment by hummingbird-dev** [comment]
I'm at the moment at a conference, but I have this on my list.

**Comment by hummingbird-dev** [comment]
Font-Awesome 5 is now supported via the hummingbird-treeview options. Please have a look at the CHANGES.md and the respective new parts of the README.md.

**Comment by armudgal** [comment]
Thanks, it's great. Also there are two `CHANGES.md` so you can take a look at that.
