### ISSUE TITLE
Converter does not support using hypens anywhere in the text of your label.

### ISSUE THREAD

**Issue by LandonHammond** [hummingbird-dev/hummingbird-treeview#2]
Converter errors if there are any hypens in the text of your checkbox label.

Throws error:

>  The item after ' + treeText + ' has too much hyphens, i.e. it is too far intended. Note that down the tree, the items are only allowed to be intended by one instance, i.e. one hyphen more than the item before. In contrast, up the tree arbitrarily large jumps are allowed.

Example markup that fails:

```
<div class="hummingbird-treeview-converter">
        <li>Warner Bros.</li>
        <li>-Goodfe-llas</li>
        <li>--Robert De Niro</li>
        <li>--Joe Pesci</li>
        <li>-The Shawshank Redemption</li>
        <li>--Tim Robbins</li>
        <li>--Morgan Freeman</li>
        <li>Paramount</li>
        <li>-The Untouchables</li>
        <li>--Robert De Niro</li>
        <li>--Kevin Costner</li>
        <li>-Forrest Gump</li>
        <li>--Tom Hanks</li>
        <li>--Robin Wright</li>
</div>
```

**Comment by hummingbird-dev** [comment]
Great catch. Thanks. I've merged your pull request.

**Comment by LandonHammond** [comment]
Cool, thanks.
