### ISSUE TITLE
reload treeview

### ISSUE THREAD

**Issue by kubickaoliver** [hummingbird-dev/hummingbird-treeview#22]
Hi, 
I would like to ask if it is possible to reload treeview from javascript, when I delete \<li\> elements and set new ones?

Thanks

**Comment by hummingbird-dev** [comment]
Hi, for these cases we have the "removeNode" and "addNode" methods. See documentation https://github.com/hummingbird-dev/hummingbird-treeview#methods or example webpage: https://hummingbird-dev.000webhostapp.com/
